woorden = [
    {
        "type": "zn",
        "duits": "das Buch",
        "meervoud": "die Bücher",
        "nederlands": "het boek",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Geburtstag",
        "meervoud": "die Geburtstage",
        "nederlands": "de verjaardag",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Leute",
        "meervoud": "-",
        "nederlands": "de mensen",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Mitschüler",
        "meervoud": "die Mitschüler",
        "nederlands": "de medeleerling",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Mitschülerin",
        "meervoud": "die Mitschülerinnen",
        "nederlands": "de medeleerling (vrouw)",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Zahl",
        "meervoud": "die Zahlen",
        "nederlands": "het getal",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "begrüßen",
        "nederlands": "begroeten",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "gehen",
        "nederlands": "gaan",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "kennen",
        "nederlands": "kennen",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "lernen",
        "nederlands": "leren",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "sagen",
        "nederlands": "zeggen",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "spielen",
        "nederlands": "spelen",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "studieren",
        "nederlands": "studeren",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "zuhören",
        "nederlands": "luisteren",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "deshalb",
        "nederlands": "daarom",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "eigentlich",
        "nederlands": "eigenlijk",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "selbstverständlich",
        "nederlands": "vanzelfsprekend",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "vielleicht",
        "nederlands": "misschien",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "zusammen",
        "nederlands": "samen",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Freund",
        "meervoud": "die Freunde",
        "nederlands": "de vriend",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Freundin",
        "meervoud": "die Freundinnen",
        "nederlands": "de vriendin",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Bewohner",
        "meervoud": "die Bewohner",
        "nederlands": "de bewoner",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Bewohnerin",
        "meervoud": "die Bewohnerinnen",
        "nederlands": "de bewoonster",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Mitbewohner",
        "meervoud": "die Mitbewohner",
        "nederlands": "de medebewoner",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Mitbewohnerin",
        "meervoud": "die Mitbewohnerinnen",
        "nederlands": "de medebewoonster",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "besuchen",
        "nederlands": "bezoeken",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "bleiben",
        "nederlands": "blijven",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "heißen",
        "nederlands": "heten",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "kommen",
        "nederlands": "komen",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "schreiben",
        "nederlands": "schrijven",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "sein",
        "nederlands": "zijn",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "sprechen",
        "nederlands": "spreken",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "wohnen",
        "nederlands": "wonen",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "haben",
        "nederlands": "hebben",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "hören",
        "nederlands": "luisteren, horen",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "kochen",
        "nederlands": "koken",
        "kapitel": "1.1"
    },
    {
        "type": "ww",
        "duits": "suchen",
        "nederlands": "zoeken",
        "kapitel": "1.1"
    },
    {
        "type": "vw",
        "duits": "was",
        "nederlands": "wat",
        "kapitel": "1.1"
    },
    {
        "type": "vw",
        "duits": "wer",
        "nederlands": "wie",
        "kapitel": "1.1"
    },
    {
        "type": "vw",
        "duits": "wie",
        "nederlands": "hoe",
        "kapitel": "1.1"
    },
    {
        "type": "vw",
        "duits": "wo",
        "nederlands": "waar",
        "kapitel": "1.1"
    },
    {
        "type": "vw",
        "duits": "woher",
        "nederlands": "waar … vandaan",
        "kapitel": "1.1"
    },
    {
        "type": "vw",
        "duits": "wohin",
        "nederlands": "waar … naartoe",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "bitte",
        "nederlands": "alstublieft",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "gut",
        "nederlands": "goed",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "prima",
        "nederlands": "prima, uitstekend",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "gern(e)",
        "nederlands": "graag",
        "kapitel": "1.1"
    },
    {
        "type": "bw",
        "duits": "schon",
        "nederlands": "al",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Name",
        "meervoud": "die Namen",
        "nederlands": "de naam",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Familienname",
        "meervoud": "die Familiennamen",
        "nederlands": "de familienaam",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Vorname",
        "meervoud": "die Vornamen",
        "nederlands": "de voornaam",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "das Land",
        "meervoud": "die Länder",
        "nederlands": "het land",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Stadt",
        "meervoud": "die Städte",
        "nederlands": "de stad",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Adresse",
        "meervoud": "die Adressen",
        "nederlands": "het adres",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Wohnort",
        "meervoud": "die Wohnorte",
        "nederlands": "de woonplaats",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "das Zimmer",
        "meervoud": "die Zimmer",
        "nederlands": "de kamer",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Belgier",
        "meervoud": "die Belgier",
        "nederlands": "de Belg",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Belgierin",
        "meervoud": "die Belgierinnen",
        "nederlands": "de Belgische",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Däne",
        "meervoud": "die Dänen",
        "nederlands": "de Deen",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Dänin",
        "meervoud": "die Däninnen",
        "nederlands": "de Deense",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Engländer",
        "meervoud": "die Engländer",
        "nederlands": "de Engelsman",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Engländerin",
        "meervoud": "die Engländerinnen",
        "nederlands": "de Engelse",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Franzose",
        "meervoud": "die Franzosen",
        "nederlands": "de Fransman",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Französin",
        "meervoud": "die Französinnen",
        "nederlands": "de Française",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Italiener",
        "meervoud": "die Italiener",
        "nederlands": "de Italiaan",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Italienerin",
        "meervoud": "die Italienerinnen",
        "nederlands": "de Italiaanse",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Luxemburger",
        "meervoud": "die Luxemburger",
        "nederlands": "de Luxemburger",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Luxemburgerin",
        "meervoud": "die Luxemburgerinnen",
        "nederlands": "de Luxemburgse",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Niederländer",
        "meervoud": "die Niederländer",
        "nederlands": "de Nederlander",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Niederländerin",
        "meervoud": "die Niederländerinnen",
        "nederlands": "de Nederlandse",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Österreicher",
        "meervoud": "die Österreicher",
        "nederlands": "de Oostenrijker",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Österreicherin",
        "meervoud": "die Österreicherinnen",
        "nederlands": "de Oostenrijkse",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Portugiese",
        "meervoud": "die Portugiesen",
        "nederlands": "de Portugees",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Portugiesin",
        "meervoud": "die Portugiesinnen",
        "nederlands": "de Portugese",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Schweizer",
        "meervoud": "die Schweizer",
        "nederlands": "de Zwitser",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Schweizerin",
        "meervoud": "die Schweizerinnen",
        "nederlands": "de Zwitserse",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Spanier",
        "meervoud": "die Spanier",
        "nederlands": "de Spanjaard",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Spanierin",
        "meervoud": "die Spanierinnen",
        "nederlands": "de Spaanse",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Muttersprache",
        "meervoud": "die Muttersprachen",
        "nederlands": "de moedertaal",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Sprache",
        "meervoud": "die Sprachen",
        "nederlands": "de taal",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Deutsch",
        "nederlands": "Duits",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Englisch",
        "nederlands": "Engels",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Französisch",
        "nederlands": "Frans",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Niederländisch",
        "nederlands": "Nederlands",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Dänisch",
        "nederlands": "Deens",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Italienisch",
        "nederlands": "Italiaans",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Portugiesisch",
        "nederlands": "Portugees",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Rätoromanisch",
        "nederlands": "Reto-Romaans",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "Spanisch",
        "nederlands": "Spaans",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Bruder",
        "meervoud": "die Brüder",
        "nederlands": "de broer",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Familie",
        "meervoud": "die Familien",
        "nederlands": "de familie",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Großmutter",
        "meervoud": "die Großmütter",
        "nederlands": "de grootmoeder",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Großvater",
        "meervoud": "die Großväter",
        "nederlands": "de grootvader",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "das Kind",
        "meervoud": "die Kinder",
        "nederlands": "het kind",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Mutter",
        "meervoud": "die Mütter",
        "nederlands": "de moeder",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Schwester",
        "meervoud": "die Schwestern",
        "nederlands": "de zus",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Sohn",
        "meervoud": "die Söhne",
        "nederlands": "de zoon",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Tochter",
        "meervoud": "die Töchter",
        "nederlands": "de dochter",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Vater",
        "meervoud": "die Väter",
        "nederlands": "de vader",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Eltern",
        "meervoud": "-",
        "nederlands": "de ouders",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Geschwister",
        "meervoud": "-",
        "nederlands": "de broers en zussen",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Großeltern",
        "meervoud": "-",
        "nederlands": "de grootouders",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "der Tag",
        "meervoud": "die Tage",
        "nederlands": "de dag",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Woche",
        "meervoud": "die Wochen",
        "nederlands": "de week",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "das Jahr",
        "meervoud": "die Jahre",
        "nederlands": "het jaar",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Zeit",
        "meervoud": "die Zeiten",
        "nederlands": "de tijd",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "das Handy",
        "meervoud": "die Handys",
        "nederlands": "de gsm",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Handynummer",
        "meervoud": "die Handynummern",
        "nederlands": "het gsm-nummer",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Nummer",
        "meervoud": "die Nummern",
        "nederlands": "het nummer",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "das Telefon",
        "meervoud": "die Telefone",
        "nederlands": "de telefoon",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "das Telefonbuch",
        "meervoud": "die Telefonbücher",
        "nederlands": "het telefoonboek",
        "kapitel": "1.1"
    },
    {
        "type": "zn",
        "duits": "die Telefonnummer",
        "meervoud": "die Telefonnummern",
        "nederlands": "het telefoonnummer",
        "kapitel": "1.1"
    },
  {"kapitel": "1.2", "type": "zn", "duits": "der Montag", "meervoud": "die Montage", "nederlands": "maandag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Dienstag", "meervoud": "die Dienstage", "nederlands": "dinsdag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Mittwoch", "meervoud": "die Mittwoche", "nederlands": "woensdag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Donnerstag", "meervoud": "die Donnerstage", "nederlands": "donderdag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Freitag", "meervoud": "die Freitage", "nederlands": "vrijdag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Samstag", "meervoud": "die Samstage", "nederlands": "zaterdag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Sonnabend", "meervoud": "die Sonnabende", "nederlands": "zaterdag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Sonntag", "meervoud": "die Sonntage", "nederlands": "zondag"},
  {"kapitel": "1.2", "type": "bw", "duits": "sonntags", "nederlands": "'s zondags"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Wochenende", "meervoud": "die Wochenenden", "nederlands": "het weekend"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Morgen", "meervoud": "die Morgen", "nederlands": "de morgen"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Vormittag", "meervoud": "die Vormittage", "nederlands": "de voormiddag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Mittag", "meervoud": "die Mittage", "nederlands": "de middag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Nachmittag", "meervoud": "die Nachmittage", "nederlands": "de namiddag"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Abend", "meervoud": "die Abende", "nederlands": "de avond"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Bahnhof", "meervoud": "die Bahnhöfe", "nederlands": "het station"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Geschäft", "meervoud": "die Geschäfte", "nederlands": "de winkel, de zaak"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Apotheke", "meervoud": "die Apotheken", "nederlands": "de apotheek"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Bank", "meervoud": "die Banken", "nederlands": "de bank"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Besuch", "meervoud": "die Besuche", "nederlands": "het bezoek"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Bibliothek", "meervoud": "die Bibliotheken", "nederlands": "de bibliotheek"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Buchhandlung", "meervoud": "die Buchhandlungen", "nederlands": "de boekhandel"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Dom", "meervoud": "die Dome", "nederlands": "de dom, de kathedraal"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Eintrittskarte", "meervoud": "die Eintrittskarten", "nederlands": "de toegangskaart"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Hotel", "meervoud": "die Hotels", "nederlands": "het hotel"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Innenstadt", "meervoud": "die Innenstädte", "nederlands": "de binnenstad"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Kirche", "meervoud": "die Kirchen", "nederlands": "de kerk"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Krankenhaus", "meervoud": "die Krankenhäuser", "nederlands": "het ziekenhuis"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Kreuzung", "meervoud": "die Kreuzungen", "nederlands": "het kruispunt"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Marktplatz", "meervoud": "die Marktplätze", "nederlands": "het marktplein"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Parkplatz", "meervoud": "die Parkplätze", "nederlands": "het parkeerterrein, de parkeerplaats"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Postamt", "meervoud": "die Postämter", "nederlands": "het postkantoor"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Programm", "meervoud": "die Programme", "nederlands": "het programma"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Rathaus", "meervoud": "die Rathäuser", "nederlands": "het stadhuis"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Restaurant", "meervoud": "die Restaurants", "nederlands": "het restaurant"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Rhein", "meervoud": "-", "nederlands": "de Rijn"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Rundgang", "meervoud": "die Rundgänge", "nederlands": "de rondleiding"},
  {"kapitel": "1.2", "type": "zn", "duits": "die S-Bahn", "meervoud": "die S-Bahnen", "nederlands": "de tram"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Stadtmitte", "meervoud": "die Stadtmitten", "nederlands": "het stadscentrum"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Theater", "meervoud": "die Theater", "nederlands": "het theater"},
  {"kapitel": "1.2", "type": "zn", "duits": "die U-Bahn", "meervoud": "die U-Bahnen", "nederlands": "de metro"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Verkehrsverein", "meervoud": "die Verkehrsvereine", "nederlands": "het toerismebureau"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Zug", "meervoud": "die Züge", "nederlands": "de trein"},
  {"kapitel": "1.2", "type": "ww", "duits": "bummeln", "nederlands": "shoppen"},
  {"kapitel": "1.2", "type": "ww", "duits": "machen", "nederlands": "doen"},
  {"kapitel": "1.2", "type": "ww", "duits": "sich treffen", "nederlands": "elkaar ontmoeten"},
  {"kapitel": "1.2", "type": "ww", "duits": "warten (auf)", "nederlands": "wachten (op)"},
  {"kapitel": "1.2", "type": "ww", "duits": "antworten", "nederlands": "antwoorden"},
  {"kapitel": "1.2", "type": "ww", "duits": "beantworten", "nederlands": "beantwoorden"},
  {"kapitel": "1.2", "type": "ww", "duits": "beginnen", "nederlands": "beginnen"},
  {"kapitel": "1.2", "type": "ww", "duits": "bieten", "nederlands": "bieden"},
  {"kapitel": "1.2", "type": "ww", "duits": "enden", "nederlands": "eindigen"},
  {"kapitel": "1.2", "type": "ww", "duits": "essen", "nederlands": "eten"},
  {"kapitel": "1.2", "type": "ww", "duits": "finden", "nederlands": "vinden"},
  {"kapitel": "1.2", "type": "ww", "duits": "holen", "nederlands": "halen"},
  {"kapitel": "1.2", "type": "ww", "duits": "können", "nederlands": "kunnen"},
  {"kapitel": "1.2", "type": "ww", "duits": "kosten", "nederlands": "kosten"},
  {"kapitel": "1.2", "type": "ww", "duits": "läuten", "nederlands": "luiden"},
  {"kapitel": "1.2", "type": "ww", "duits": "nehmen", "nederlands": "nemen"},
  {"kapitel": "1.2", "type": "ww", "duits": "übertreiben", "nederlands": "overdrijven"},
  {"kapitel": "1.2", "type": "bw", "duits": "früher", "nederlands": "vroeger"},
  {"kapitel": "1.2", "type": "bw", "duits": "gestern", "nederlands": "gisteren"},
  {"kapitel": "1.2", "type": "bw", "duits": "heute", "nederlands": "vandaag"},
  {"kapitel": "1.2", "type": "bw", "duits": "morgen", "nederlands": "morgen"},
  {"kapitel": "1.2", "type": "bw", "duits": "übermorgen", "nederlands": "overmorgen"},
  {"kapitel": "1.2", "type": "bw", "duits": "später", "nederlands": "later"},
  {"kapitel": "1.2", "type": "bw", "duits": "vielleicht", "nederlands": "misschien"},
  {"kapitel": "1.2", "type": "bw", "duits": "auf jeden Fall", "nederlands": "in elk geval"},
  {"kapitel": "1.2", "type": "bw", "duits": "danach", "nederlands": "daarna"},
  {"kapitel": "1.2", "type": "bw", "duits": "dann", "nederlands": "dan"},
  {"kapitel": "1.2", "type": "bw", "duits": "dort", "nederlands": "daar"},
  {"kapitel": "1.2", "type": "bw", "duits": "ein wenig", "nederlands": "een beetje"},
  {"kapitel": "1.2", "type": "bw", "duits": "geradeaus", "nederlands": "rechtdoor"},
  {"kapitel": "1.2", "type": "bw", "duits": "lange", "nederlands": "lang"},
  {"kapitel": "1.2", "type": "bw", "duits": "nur", "nederlands": "slechts, maar"},
  {"kapitel": "1.2", "type": "bw", "duits": "schön", "nederlands": "mooi"},
  {"kapitel": "1.2", "type": "bw", "duits": "unbedingt", "nederlands": "absoluut"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Auskunft", "meervoud": "die Auskünfte", "nederlands": "de inlichting"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Brief", "meervoud": "die Briefe", "nederlands": "de brief"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Film", "meervoud": "die Filme", "nederlands": "de film"},
  {"kapitel": "1.2", "type": "zn", "duits": "das Frühstück", "meervoud": "die Frühstücke", "nederlands": "het ontbijt"},
  {"kapitel": "1.2", "type": "zn", "duits": "der Schreibtisch", "meervoud": "die Schreibtische", "nederlands": "de schrijftafel, het bureau"},
  {"kapitel": "1.2", "type": "zn", "duits": "die Stunde", "meervoud": "die Stunden", "nederlands": "het uur (de tijdsduur)"},
  {"kapitel": "1.2", "type": "ww", "duits": "bitten", "nederlands": "vragen"},
  {"kapitel": "1.2", "type": "ww", "duits": "einschalten", "nederlands": "aansteken, opzetten"},
  {"kapitel": "1.2", "type": "ww", "duits": "frühstücken", "nederlands": "ontbijten"},
  {"kapitel": "1.2", "type": "ww", "duits": "Klavier spielen", "nederlands": "pianospelen"},
  {"kapitel": "1.2", "type": "ww", "duits": "reden", "nederlands": "spreken"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Banane", "meervoud": "die Bananen", "nederlands": "de banaan"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Bier", "meervoud": "die Biere", "nederlands": "het bier"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Brötchen", "meervoud": "die Brötchen", "nederlands": "het broodje"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Cola", "meervoud": "die Colas", "nederlands": "de cola"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Ei", "meervoud": "die Eier", "nederlands": "het ei"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Kaffee", "meervoud": "die Kaffees", "nederlands": "de koffie"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Kuchen", "meervoud": "die Kuchen", "nederlands": "de taart"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Mahlzeit", "meervoud": "die Mahlzeiten", "nederlands": "de maaltijd"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Pizza", "meervoud": "die Pizzen / Pizzas", "nederlands": "de pizza"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Pommes", "meervoud": "-", "nederlands": "frieten"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Tüte", "meervoud": "die Tüten", "nederlands": "de zak"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Schule", "meervoud": "die Schulen", "nederlands": "de school"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Sport", "meervoud": "-", "nederlands": "de sport"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Unterricht", "meervoud": "-", "nederlands": "de les"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Chemie", "nederlands": "chemie"},
  {"kapitel": "1.3", "type": "zn", "duits": "Englisch", "nederlands": "Engels"},
  {"kapitel": "1.3", "type": "zn", "duits": "Französisch", "nederlands": "Frans"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Geografie", "nederlands": "aardrijkskunde"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Geschichte", "nederlands": "geschiedenis"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Lieblingsfach", "meervoud": "die Lieblingsfächer", "nederlands": "het lievelingsvak"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Mathe(matik)", "nederlands": "wiskunde"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Musik", "nederlands": "muziek"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Physik", "nederlands": "fysica"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Religion", "nederlands": "godsdienst"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Stunde", "meervoud": "die Stunden", "nederlands": "het lesuur"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Stundenplan", "meervoud": "die Stundenpläne", "nederlands": "het lessenrooster"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Bioladen", "meervoud": "die Bioläden", "nederlands": "de biowinkel"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Hobby", "meervoud": "die Hobbys", "nederlands": "de hobby"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Körper", "meervoud": "die Körper", "nederlands": "het lichaam"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Nachbarschaft", "meervoud": "die Nachbarschaften", "nederlands": "de buurt"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Navi", "meervoud": "die Navis", "nederlands": "de gps"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Ort", "meervoud": "die Orte", "nederlands": "de plaats"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Quatsch", "meervoud": "-", "nederlands": "de onzin"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Sicherung", "meervoud": "die Sicherungen", "nederlands": "de beveiliging"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Sport", "meervoud": "-", "nederlands": "de sport"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Umwelt", "meervoud": "-", "nederlands": "het milieu"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Wochenende", "meervoud": "die Wochenenden", "nederlands": "het weekend"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Ziel", "meervoud": "die Ziele", "nederlands": "het doel, de finish"},
  {"kapitel": "1.3", "type": "ww", "duits": "anfangen", "nederlands": "beginnen"},
  {"kapitel": "1.3", "type": "ww", "duits": "aufstehen", "nederlands": "opstaan"},
  {"kapitel": "1.3", "type": "ww", "duits": "einladen", "nederlands": "uitnodigen"},
  {"kapitel": "1.3", "type": "ww", "duits": "fahren", "nederlands": "rijden"},
  {"kapitel": "1.3", "type": "ww", "duits": "lassen", "nederlands": "laten"},
  {"kapitel": "1.3", "type": "ww", "duits": "laufen", "nederlands": "lopen"},
  {"kapitel": "1.3", "type": "ww", "duits": "schlafen", "nederlands": "slapen"},
  {"kapitel": "1.3", "type": "ww", "duits": "trinken", "nederlands": "drinken"},
  {"kapitel": "1.3", "type": "ww", "duits": "verlassen", "nederlands": "verlaten"},
  {"kapitel": "1.3", "type": "ww", "duits": "essen", "nederlands": "eten"},
  {"kapitel": "1.3", "type": "ww", "duits": "geben", "nederlands": "geven"},
  {"kapitel": "1.3", "type": "ww", "duits": "lesen", "nederlands": "lezen"},
  {"kapitel": "1.3", "type": "ww", "duits": "nehmen", "nederlands": "nemen"},
  {"kapitel": "1.3", "type": "ww", "duits": "sehen", "nederlands": "zien"},
  {"kapitel": "1.3", "type": "ww", "duits": "sprechen", "nederlands": "spreken"},
  {"kapitel": "1.3", "type": "ww", "duits": "treffen", "nederlands": "ontmoeten"},
  {"kapitel": "1.3", "type": "ww", "duits": "vergessen", "nederlands": "vergeten"},
  {"kapitel": "1.3", "type": "ww", "duits": "klettern", "nederlands": "klimmen"},
  {"kapitel": "1.3", "type": "ww", "duits": "schaffen", "nederlands": "klaarspelen"},
  {"kapitel": "1.3", "type": "bw", "duits": "immer", "nederlands": "altijd"},
  {"kapitel": "1.3", "type": "bw", "duits": "manchmal", "nederlands": "soms"},
  {"kapitel": "1.3", "type": "bw", "duits": "nie", "nederlands": "nooit"},
  {"kapitel": "1.3", "type": "bw", "duits": "oft", "nederlands": "vaak, dikwijls"},
  {"kapitel": "1.3", "type": "bw", "duits": "selten", "nederlands": "zelden"},
  {"kapitel": "1.3", "type": "adj", "duits": "abenteuerlich", "nederlands": "avontuurlijk"},
  {"kapitel": "1.3", "type": "adj", "duits": "krass", "nederlands": "te gek"},
  {"kapitel": "1.3", "type": "bw", "duits": "überhaupt", "nederlands": "over het algemeen, helemaal"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Bus", "meervoud": "die Busse", "nederlands": "de bus"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Fahrrad", "meervoud": "die Fahrräder", "nederlands": "de fiets"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Hotelzimmer", "meervoud": "die Hotelzimmer", "nederlands": "de hotelkamer"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Hund", "meervoud": "die Hunde", "nederlands": "de hond"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Katze", "meervoud": "die Katzen", "nederlands": "de kat"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Koffer", "meervoud": "die Koffer", "nederlands": "de koffer"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Kreditkarte", "meervoud": "die Kreditkarten", "nederlands": "de kredietkaart"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Kugelschreiber (Kuli)", "meervoud": "die Kugelschreiber (Kulis)", "nederlands": "de balpen"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Laptop", "meervoud": "die Laptops", "nederlands": "de laptop"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Moped", "meervoud": "die Mopeds", "nederlands": "de bromfiets"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Mountainbike", "meervoud": "die Mountainbikes", "nederlands": "de mountainbike"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Portemonnaie", "meervoud": "die Portemonnaies", "nederlands": "de portemonnee"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Radiergummi", "meervoud": "die Radiergummis", "nederlands": "de gom"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Regenjacke", "meervoud": "die Regenjacken", "nederlands": "de regenjas"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Regenschirm", "meervoud": "die Regenschirme", "nederlands": "de paraplu"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Reiseführer", "meervoud": "die Reiseführer", "nederlands": "de reisgids"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Reisepass", "meervoud": "die Reisepässe", "nederlands": "de reispas"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Smartphone", "meervoud": "die Smartphones", "nederlands": "de smartphone"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Sonnenbrille", "meervoud": "die Sonnenbrillen", "nederlands": "de zonnebril"},
  {"kapitel": "1.3", "type": "zn", "duits": "der Stadtplan", "meervoud": "die Stadtpläne", "nederlands": "het stadsplan"},
  {"kapitel": "1.3", "type": "zn", "duits": "das Wörterbuch", "meervoud": "die Wörterbücher", "nederlands": "het woordenboek"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Zahnbürste", "meervoud": "die Zahnbürsten", "nederlands": "de tandenborstel"},
  {"kapitel": "1.3", "type": "zn", "duits": "die Zeitschrift", "meervoud": "die Zeitschriften", "nederlands": "het tijdschrift"},
  {"kapitel": "1.3", "type": "ww", "duits": "ausgeben", "nederlands": "uitgeven"},
  {"kapitel": "1.3", "type": "ww", "duits": "bestellen", "nederlands": "bestellen"},
  {"kapitel": "1.3", "type": "ww", "duits": "fernsehen", "nederlands": "tv-kijken"},
  {"kapitel": "1.3", "type": "adj", "duits": "billig", "nederlands": "goedkoop"},
  {"kapitel": "1.3", "type": "bw", "duits": "ein bisschen", "nederlands": "een beetje"},
  {"kapitel": "1.3", "type": "adj", "duits": "gesund", "nederlands": "gezond"},
  {"kapitel": "1.3", "type": "bw", "duits": "hoffentlich", "nederlands": "hopelijk"},
  {"kapitel": "1.3", "type": "adj", "duits": "schwierig", "nederlands": "moeilijk"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Einladung", "meervoud": "die Einladungen", "nederlands": "de uitnodiging"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Geburtstag", "meervoud": "die Geburtstage", "nederlands": "de verjaardag"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Geburtstagsparty", "meervoud": "die Geburtstagspartys", "nederlands": "het verjaardagsfeestje"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Party", "meervoud": "die Partys", "nederlands": "het feestje, de party"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Stimmung", "meervoud": "die Stimmungen", "nederlands": "de stemming"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Badeanzug", "meervoud": "die Badeanzüge", "nederlands": "het badpak"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Badehose", "meervoud": "die Badehosen", "nederlands": "de zwembroek"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Brille", "meervoud": "die Brillen", "nederlands": "de bril"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Comic", "meervoud": "die Comics", "nederlands": "het stripverhaal"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Computerspiel", "meervoud": "die Computerspiele", "nederlands": "de game, het computerspel"},
  {"kapitel": "1.4", "type": "zn", "duits": "die DVD", "meervoud": "die DVDs", "nederlands": "de dvd"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Flasche", "meervoud": "die Flaschen", "nederlands": "de fles"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Fußball", "meervoud": "die Fußbälle", "nederlands": "de voetbal"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Fußballschuh", "meervoud": "die Fußballschuhe", "nederlands": "de voetbalschoen"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Geschenk", "meervoud": "die Geschenke", "nederlands": "het geschenk"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Gutschein", "meervoud": "die Gutscheine", "nederlands": "de waardebon"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Kamera", "meervoud": "die Kameras", "nederlands": "de camera"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Paar", "meervoud": "die Paare", "nederlands": "het paar"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Rucksack", "meervoud": "die Rucksäcke", "nederlands": "de rugzak"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Schal", "meervoud": "die Schals", "nederlands": "de sjaal"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Tablet", "meervoud": "die Tablets", "nederlands": "de tablet"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Tagebuch", "meervoud": "die Tagebücher", "nederlands": "het dagboek"},
  {"kapitel": "1.4", "type": "zn", "duits": "das T-Shirt", "meervoud": "die T-Shirts", "nederlands": "het T-shirt"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Zeitschrift", "meervoud": "die Zeitschriften", "nederlands": "het tijdschrift"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Zeitung", "meervoud": "die Zeitungen", "nederlands": "de krant"},
  {"kapitel": "1.4", "type": "ww", "duits": "einladen", "nederlands": "uitnodigen"},
  {"kapitel": "1.4", "type": "ww", "duits": "erwarten", "nederlands": "verwachten"},
  {"kapitel": "1.4", "type": "ww", "duits": "feiern", "nederlands": "vieren, feesten"},
  {"kapitel": "1.4", "type": "ww", "duits": "gratulieren", "nederlands": "feliciteren"},
  {"kapitel": "1.4", "type": "ww", "duits": "mitbringen", "nederlands": "meebrengen"},
  {"kapitel": "1.4", "type": "ww", "duits": "schicken", "nederlands": "zenden, sturen"},
  {"kapitel": "1.4", "type": "ww", "duits": "basteln", "nederlands": "knutselen"},
  {"kapitel": "1.4", "type": "ww", "duits": "geraten", "nederlands": "geraken"},
  {"kapitel": "1.4", "type": "ww", "duits": "herausfinden", "nederlands": "te weten komen"},
  {"kapitel": "1.4", "type": "ww", "duits": "herumlaufen", "nederlands": "rondlopen"},
  {"kapitel": "1.4", "type": "ww", "duits": "klingen", "nederlands": "klinken"},
  {"kapitel": "1.4", "type": "ww", "duits": "fallen", "nederlands": "vallen"},
  {"kapitel": "1.4", "type": "ww", "duits": "gehen", "nederlands": "gaan"},
  {"kapitel": "1.4", "type": "ww", "duits": "helfen", "nederlands": "helpen"},
  {"kapitel": "1.4", "type": "ww", "duits": "schlafen", "nederlands": "slapen"},
  {"kapitel": "1.4", "type": "ww", "duits": "singen", "nederlands": "zingen"},
  {"kapitel": "1.4", "type": "ww", "duits": "tanzen", "nederlands": "dansen"},
  {"kapitel": "1.4", "type": "ww", "duits": "verlieren", "nederlands": "verliezen"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Arbeit", "meervoud": "die Arbeiten", "nederlands": "het werk"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Feuerwerk", "meervoud": "die Feuerwerke", "nederlands": "het vuurwerk"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Gemüsegarten", "meervoud": "die Gemüsegärten", "nederlands": "de groentetuin"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Gesellschaftsspiel", "meervoud": "die Gesellschaftsspiele", "nederlands": "het gezelschapsspel"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Halskette", "meervoud": "die Halsketten", "nederlands": "de halsketting"},
  {"kapitel": "1.4", "type": "zn", "duits": "das Hörbuch", "meervoud": "die Hörbücher", "nederlands": "het luisterboek"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Kopfhörer", "meervoud": "die Kopfhörer", "nederlands": "de koptelefoon"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Kriminalroman / Krimi", "meervoud": "die Kriminalromane / Krimis", "nederlands": "de misdaadroman"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Lederjacke", "meervoud": "die Lederjacken", "nederlands": "de leren jas"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Schallplatte", "meervoud": "die Schallplatten", "nederlands": "de (vinyl)plaat"},
  {"kapitel": "1.4", "type": "zn", "duits": "der Tennisschläger", "meervoud": "die Tennisschläger", "nederlands": "het tennisracket"},
  {"kapitel": "1.4", "type": "zn", "duits": "die Wohnung", "meervoud": "die Wohnungen", "nederlands": "het appartement"},
  {"kapitel": "1.4", "type": "ww", "duits": "aufräumen", "nederlands": "opruimen"},
  {"kapitel": "1.4", "type": "ww", "duits": "putzen", "nederlands": "schoonmaken"},
  {"kapitel": "1.4", "type": "ww", "duits": "sich verletzen", "nederlands": "zich verwonden"},
  {"kapitel": "1.4", "type": "ww", "duits": "spülen", "nederlands": "afwassen"},
  {"kapitel": "1.4", "type": "ww", "duits": "staubsaugen", "nederlands": "stofzuigen"},
  {"kapitel": "1.4", "type": "bw", "duits": "bestimmt", "nederlands": "beslist"},
  {"kapitel": "1.4", "type": "bw", "duits": "ein bisschen", "nederlands": "een beetje"},
  {"kapitel": "1.4", "type": "bw", "duits": "rechtzeitig", "nederlands": "op tijd, tijdig"},
  {"kapitel": "1.4", "type": "adj", "duits": "sauber", "nederlands": "net, schoon"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Gemüse", "meervoud": "die Gemüse", "nederlands": "de groente"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Gurke", "meervoud": "die Gurken", "nederlands": "de komkommer"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Karotte", "meervoud": "die Karotten", "nederlands": "de wortel"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Kürbis", "meervoud": "die Kürbisse", "nederlands": "de pompoen"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Petersilie", "meervoud": "-", "nederlands": "de peterselie"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Radieschen", "meervoud": "die Radieschen", "nederlands": "de radijs"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Rosenkohl", "meervoud": "-", "nederlands": "de spruitjes"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Rotkohl", "meervoud": "-", "nederlands": "de rode kool"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Salat", "meervoud": "die Salate", "nederlands": "de sla"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Spargel", "meervoud": "die Spargel", "nederlands": "de asperge"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Tomate", "meervoud": "die Tomaten", "nederlands": "de tomaat"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Zucchini", "meervoud": "die Zucchini", "nederlands": "de courgette"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Zwiebel", "meervoud": "die Zwiebeln", "nederlands": "de ui"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Apfel", "meervoud": "die Äpfel", "nederlands": "de appel"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Banane", "meervoud": "die Bananen", "nederlands": "de banaan"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Birne", "meervoud": "die Birnen", "nederlands": "de peer"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Erdbeere", "meervoud": "die Erdbeeren", "nederlands": "de aardbei"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Grapefruit", "meervoud": "die Grapefruits", "nederlands": "de pompelmoes"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Kirsche", "meervoud": "die Kirschen", "nederlands": "de kers"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Kiwi", "meervoud": "die Kiwis", "nederlands": "de kiwi"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Mango", "meervoud": "die Mangos", "nederlands": "de mango"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Orange", "meervoud": "die Orangen", "nederlands": "de sinaasappel"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Pfirsich", "meervoud": "die Pfirsiche", "nederlands": "de perzik"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Pflaume", "meervoud": "die Pflaumen", "nederlands": "de pruim"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Traube", "meervoud": "die Trauben", "nederlands": "de druif"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Bier", "meervoud": "die Biere", "nederlands": "het bier"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Cola", "meervoud": "die Colas", "nederlands": "de cola"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Getränk", "meervoud": "die Getränke", "nederlands": "de drank"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Joghurt", "meervoud": "die Joghurts", "nederlands": "de yoghurt"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Kaffee", "meervoud": "die Kaffees", "nederlands": "de koffie"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Milch", "meervoud": "-", "nederlands": "de melk"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Orangensaft", "meervoud": "die Orangensäfte", "nederlands": "het sinaasappelsap"},
  {"kapitel": "1.5", "type": "zn", "duits": "der O-Saft", "meervoud": "die O-Säfte", "nederlands": "het sinaasappelsap"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Tee", "meervoud": "die Tees", "nederlands": "de thee"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Wasser", "meervoud": "die Wässer", "nederlands": "het water"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Wein", "meervoud": "die Weine", "nederlands": "de wijn"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Brot", "meervoud": "die Brote", "nederlands": "het brood"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Brötchen", "meervoud": "die Brötchen", "nederlands": "het broodje"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Butter", "meervoud": "-", "nederlands": "de boter"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Ei", "meervoud": "die Eier", "nederlands": "het ei"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Fleisch", "meervoud": "-", "nederlands": "het vlees"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Käse", "meervoud": "die Käse", "nederlands": "de kaas"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Marmelade", "meervoud": "die Marmeladen", "nederlands": "de marmelade, jam"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Schinken", "meervoud": "die Schinken", "nederlands": "de ham"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Schnitzel", "meervoud": "die Schnitzel", "nederlands": "de schnitzel"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Wurst", "meervoud": "die Würste", "nederlands": "de worst"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Fisch", "meervoud": "die Fische", "nederlands": "de vis"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Kartoffel", "meervoud": "die Kartoffeln", "nederlands": "de aardappel"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Nudel", "meervoud": "die Nudeln", "nederlands": "de pasta"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Gabel", "meervoud": "die Gabeln", "nederlands": "de vork"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Glas", "meervoud": "die Gläser", "nederlands": "het glas"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Löffel", "meervoud": "die Löffel", "nederlands": "de lepel"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Messer", "meervoud": "die Messer", "nederlands": "het mes"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Tasse", "meervoud": "die Tassen", "nederlands": "het kopje, de tas"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Teller", "meervoud": "die Teller", "nederlands": "het bord"},
  {"kapitel": "1.5", "type": "ww", "duits": "mögen", "nederlands": "lusten, graag hebben, graag eten"},
  {"kapitel": "1.5", "type": "ww", "duits": "werden", "nederlands": "zullen"},
  {"kapitel": "1.5", "type": "ww", "duits": "werden", "nederlands": "worden"},
  {"kapitel": "1.5", "type": "ww", "duits": "wissen", "nederlands": "weten"},
  {"kapitel": "1.5", "type": "ww", "duits": "empfehlen", "nederlands": "aanraden"},
  {"kapitel": "1.5", "type": "ww", "duits": "gefallen", "nederlands": "bevallen"},
  {"kapitel": "1.5", "type": "ww", "duits": "schmecken", "nederlands": "smaken"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Dose", "meervoud": "die Dosen", "nederlands": "het blik"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Flasche", "meervoud": "die Flaschen", "nederlands": "de fles"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Gericht", "meervoud": "die Gerichte", "nederlands": "het gerecht"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Koch", "meervoud": "die Köche", "nederlands": "de kok"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Kochbuch", "meervoud": "die Kochbücher", "nederlands": "het kookboek"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Korb", "meervoud": "die Körbe", "nederlands": "de mand"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Mittagessen", "meervoud": "die Mittagessen", "nederlands": "het middagmaal"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Nachspeise", "meervoud": "die Nachspeisen", "nederlands": "het nagerecht"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Pommes (frites)", "meervoud": "-", "nederlands": "frietjes"},
  {"kapitel": "1.5", "type": "zn", "duits": "das Rezept", "meervoud": "die Rezepte", "nederlands": "het recept"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Soße", "meervoud": "die Soßen", "nederlands": "de saus"},
  {"kapitel": "1.5", "type": "zn", "duits": "die Stofftüte", "meervoud": "die Stofftüten", "nederlands": "de stoffen zak"},
  {"kapitel": "1.5", "type": "zn", "duits": "der Wochenmarkt", "meervoud": "die Wochenmärkte", "nederlands": "de weekmarkt"},
  {"kapitel": "1.5", "type": "ww", "duits": "ausprobieren", "nederlands": "uittesten"},
  {"kapitel": "1.5", "type": "ww", "duits": "brauchen", "nederlands": "nodig hebben"},
  {"kapitel": "1.5", "type": "ww", "duits": "einkaufen", "nederlands": "inkopen doen"},
  {"kapitel": "1.5", "type": "ww", "duits": "ernten", "nederlands": "oogsten"},
  {"kapitel": "1.5", "type": "ww", "duits": "schätzen", "nederlands": "waarderen"},
  {"kapitel": "1.5", "type": "ww", "duits": "zubereiten", "nederlands": "bereiden"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Auskunft", "meervoud": "die Auskünfte", "nederlands": "de inlichting"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Frage", "meervoud": "die Fragen", "nederlands": "de vraag"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Information", "meervoud": "die Informationen", "nederlands": "de informatie"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Frau", "meervoud": "die Frauen", "nederlands": "de vrouw, mevrouw"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Herr", "meervoud": "die Herren", "nederlands": "de heer, meneer"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Sommerferien", "meervoud": "-", "nederlands": "de zomervakantie"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Freizeit", "meervoud": "die Freizeiten", "nederlands": "de vrije tijd"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Reise", "meervoud": "die Reisen", "nederlands": "de reis"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Aushilfe", "meervoud": "die Aushilfen", "nederlands": "de hulpkracht, jobstudent"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Ferienjob", "meervoud": "die Ferienjobs", "nederlands": "de vakantiejob"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Ferienjobber", "meervoud": "die Ferienjobber", "nederlands": "de jobstudent"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Aufgabe", "meervoud": "die Aufgaben", "nederlands": "de taak, de opdracht"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Erfahrung", "meervoud": "die Erfahrungen", "nederlands": "de ervaring"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Geld", "meervoud": "die Gelder", "nederlands": "het geld"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Kunde", "meervoud": "die Kunden", "nederlands": "de klant"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Mitarbeiter", "meervoud": "die Mitarbeiter", "nederlands": "de medewerker"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Modeladen", "meervoud": "die Modeläden", "nederlands": "de modewinkel"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Drittel", "meervoud": "die Drittel", "nederlands": "het derde"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Prozent", "meervoud": "die Prozente", "nederlands": "het procent"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Schätzung", "meervoud": "die Schätzungen", "nederlands": "de schatting, de raming"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Umfrage", "meervoud": "die Umfragen", "nederlands": "de enquête"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Selbstständigkeit", "meervoud": "die Selbstständigkeiten", "nederlands": "de zelfstandigheid"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Unabhängigkeit", "meervoud": "die Unabhängigkeiten", "nederlands": "de onafhankelijkheid"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Beispiel", "meervoud": "die Beispiele", "nederlands": "het voorbeeld"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Nachteil", "meervoud": "die Nachteile", "nederlands": "het nadeel"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Vorteil", "meervoud": "die Vorteile", "nederlands": "het voordeel"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Wunsch", "meervoud": "die Wünsche", "nederlands": "de wens"},
  {"kapitel": "1.6", "type": "ww", "duits": "anrufen", "nederlands": "opbellen"},
  {"kapitel": "1.6", "type": "ww", "duits": "arbeiten", "nederlands": "werken"},
  {"kapitel": "1.6", "type": "ww", "duits": "brauchen", "nederlands": "nodig hebben"},
  {"kapitel": "1.6", "type": "ww", "duits": "dürfen", "nederlands": "mogen"},
  {"kapitel": "1.6", "type": "ww", "duits": "verdienen", "nederlands": "verdienen"},
  {"kapitel": "1.6", "type": "ww", "duits": "wissen", "nederlands": "weten"},
  {"kapitel": "1.6", "type": "ww", "duits": "auspacken", "nederlands": "uitpakken"},
  {"kapitel": "1.6", "type": "ww", "duits": "austragen", "nederlands": "bezorgen, rondbrengen"},
  {"kapitel": "1.6", "type": "ww", "duits": "erfüllen", "nederlands": "vervullen"},
  {"kapitel": "1.6", "type": "ww", "duits": "fördern", "nederlands": "bevorderen"},
  {"kapitel": "1.6", "type": "ww", "duits": "gefallen", "nederlands": "bevallen"},
  {"kapitel": "1.6", "type": "ww", "duits": "lassen", "nederlands": "laten"},
  {"kapitel": "1.6", "type": "ww", "duits": "lieben", "nederlands": "houden van"},
  {"kapitel": "1.6", "type": "ww", "duits": "planen", "nederlands": "plannen"},
  {"kapitel": "1.6", "type": "ww", "duits": "sammeln", "nederlands": "verzamelen"},
  {"kapitel": "1.6", "type": "ww", "duits": "sich ändern", "nederlands": "veranderen"},
  {"kapitel": "1.6", "type": "ww", "duits": "umgehen", "nederlands": "omgaan"},
  {"kapitel": "1.6", "type": "ww", "duits": "vernachlässigen", "nederlands": "verwaarlozen"},
  {"kapitel": "1.6", "type": "ww", "duits": "verteilen", "nederlands": "verdelen, uitdelen"},
  {"kapitel": "1.6", "type": "vw", "duits": "aber", "nederlands": "maar, echter"},
  {"kapitel": "1.6", "type": "bw", "duits": "gerade", "nederlands": "(daar)net"},
  {"kapitel": "1.6", "type": "bw", "duits": "höchstens", "nederlands": "hoogstens"},
  {"kapitel": "1.6", "type": "vw", "duits": "nämlich", "nederlands": "namelijk, immers"},
  {"kapitel": "1.6", "type": "vw", "duits": "ob", "nederlands": "of"},
  {"kapitel": "1.6", "type": "vz", "duits": "pro", "nederlands": "per"},
  {"kapitel": "1.6", "type": "vw", "duits": "wenn", "nederlands": "als, indien"},
  {"kapitel": "1.6", "type": "bw", "duits": "außerdem", "nederlands": "bovendien"},
  {"kapitel": "1.6", "type": "adj", "duits": "bundesweit", "nederlands": "in de hele Bondsrepubliek"},
  {"kapitel": "1.6", "type": "vw", "duits": "denn", "nederlands": "want"},
  {"kapitel": "1.6", "type": "bw", "duits": "dreimal", "nederlands": "driemaal"},
  {"kapitel": "1.6", "type": "adj", "duits": "eigen", "nederlands": "eigen"},
  {"kapitel": "1.6", "type": "telw", "duits": "eineinhalb", "nederlands": "anderhalf"},
  {"kapitel": "1.6", "type": "bw", "duits": "knapp", "nederlands": "bijna, iets minder dan"},
  {"kapitel": "1.6", "type": "adj", "duits": "langweilig", "nederlands": "saai"},
  {"kapitel": "1.6", "type": "adj", "duits": "nervig", "nederlands": "vervelend"},
  {"kapitel": "1.6", "type": "adj", "duits": "nett", "nederlands": "aardig"},
  {"kapitel": "1.6", "type": "adj", "duits": "schnell", "nederlands": "snel"},
  {"kapitel": "1.6", "type": "bw", "duits": "sogar", "nederlands": "zelfs"},
  {"kapitel": "1.6", "type": "bw", "duits": "teilweise", "nederlands": "gedeeltelijk"},
  {"kapitel": "1.6", "type": "bw", "duits": "unterwegs", "nederlands": "onderweg"},
  {"kapitel": "1.6", "type": "vw", "duits": "weil", "nederlands": "omdat"},
  {"kapitel": "1.6", "type": "adj", "duits": "wöchentlich", "nederlands": "wekelijks"},
  {"kapitel": "1.6", "type": "telw", "duits": "zweieinhalb", "nederlands": "tweeënhalf"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Ausland", "meervoud": "-", "nederlands": "het buitenland"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Kasse", "meervoud": "die Kassen", "nederlands": "de kassa"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Klima", "meervoud": "die Klimas", "nederlands": "het klimaat"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Licht", "meervoud": "die Lichter", "nederlands": "het licht"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Lieferung", "meervoud": "die Lieferungen", "nederlands": "de levering"},
  {"kapitel": "1.6", "type": "zn", "duits": "die Luft", "meervoud": "-", "nederlands": "de lucht"},
  {"kapitel": "1.6", "type": "zn", "duits": "das Medikament", "meervoud": "die Medikamente", "nederlands": "het geneesmiddel"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Pullover", "meervoud": "die Pullover", "nederlands": "de pullover, de trui"},
  {"kapitel": "1.6", "type": "zn", "duits": "der Regen", "meervoud": "die Regen", "nederlands": "de regen"},
  {"kapitel": "1.6", "type": "ww", "duits": "aufpassen", "nederlands": "oppassen, opletten"},
  {"kapitel": "1.6", "type": "ww", "duits": "bekommen", "nederlands": "krijgen"},
  {"kapitel": "1.6", "type": "ww", "duits": "bestehen", "nederlands": "bestaan"},
  {"kapitel": "1.6", "type": "ww", "duits": "bezahlen", "nederlands": "betalen"},
  {"kapitel": "1.6", "type": "ww", "duits": "durchstellen", "nederlands": "doorverbinden"},
  {"kapitel": "1.6", "type": "ww", "duits": "erklären", "nederlands": "verklaren"},
  {"kapitel": "1.6", "type": "ww", "duits": "erzählen", "nederlands": "vertellen"},
  {"kapitel": "1.6", "type": "ww", "duits": "legen", "nederlands": "leggen"},
  {"kapitel": "1.6", "type": "ww", "duits": "liefern", "nederlands": "leveren"},
  {"kapitel": "1.6", "type": "ww", "duits": "notieren", "nederlands": "noteren"},
  {"kapitel": "1.6", "type": "vz", "duits": "ab", "nederlands": "vanaf"},
  {"kapitel": "1.6", "type": "adj", "duits": "beliebt", "nederlands": "geliefd, populair"},
  {"kapitel": "1.6", "type": "bw", "duits": "ein paar", "nederlands": "een paar"},
  {"kapitel": "1.6", "type": "bw", "duits": "etwa", "nederlands": "ongeveer"},
  {"kapitel": "1.6", "type": "bw", "duits": "extra", "nederlands": "extra"},
  {"kapitel": "1.6", "type": "adj", "duits": "fertig", "nederlands": "klaar"},
  {"kapitel": "1.6", "type": "adj", "duits": "fest", "nederlands": "vast"},
  {"kapitel": "1.6", "type": "adj", "duits": "genau", "nederlands": "precies, juist"},
  {"kapitel": "1.6", "type": "bw", "duits": "mehr", "nederlands": "meer"},
  {"kapitel": "1.6", "type": "bw", "duits": "nur", "nederlands": "slechts"},
  {"kapitel": "1.6", "type": "bw", "duits": "selber", "nederlands": "zelf"},
  {"kapitel": "1.6", "type": "bw", "duits": "sonst", "nederlands": "anders"},
  {"kapitel": "1.6", "type": "bw", "duits": "ungefähr", "nederlands": "ongeveer"},
  {"kapitel": "1.6", "type": "adj", "duits": "ungewöhnlich", "nederlands": "ongewoon"},
  {"kapitel": "1.6", "type": "bw", "duits": "wirklich", "nederlands": "werkelijk"}
]